apiVersion: v1
kind: Node
metadata:
  labels:
    beta.kubernetes.io/arch: intel
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: intel
    kubernetes.io/hostname: minikube
    kubernetes.io/os: linux
    node-role.kubernetes.io/master: ''
    alibabacloud.com/gpu-card-model: V100
  name: new-node
status:
  allocatable:
    alibabacloud.com/gpu-count: '8'
    alibabacloud.com/gpu-mem: 130240Mi
    cpu: 128
    memory: 512000Mi
    pods: '200'
  capacity:
    alibabacloud.com/gpu-count: '8'
    alibabacloud.com/gpu-mem: 130240Mi
    cpu: 128
    memory: 512000Mi
    pods: '200'