apiVersion: v1
kind: Pod
metadata:
  name: isw-pod-00
  namespace: isw-gpu
  annotations:
    alibabacloud.com/gpu-mem: 10240Mi
    alibabacloud.com/gpu-count: "1"
spec:
  containers:
    - image: tensorflow:latest
      name: main
      resources:
        limits:
          cpu: 96
          memory: 9216Mi
        requests:
          cpu: 96
          memory: 9216Mi